<a href="https://colab.research.google.com/github/C-Duberry/Data-Analysis-Portfolio/blob/main/python_datax.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
from google.colab import files
upload = files.upload()

Saving student.csv to student.csv

In [12]:
df = pd.read_csv("student.csv")

In [13]:
df.head()

   id        name  class  mark  gender
0   1    John Deo   Four    75  female
1   2    Max Ruin  Three    85    male
2   3      Arnold  Three    55    male
3   4  Krish Star   Four    60  female
4   5   John Mike   Four    60  female

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      35 non-null     int64
 1   name    34 non-null     object
 2   class   34 non-null     object
 3   mark    35 non-null     int64
 4   gender  33 non-null     object
dtypes: int64(2), object(3)
memory usage: 1.5+ KB

In [14]:
df.describe()

              id       mark
count  35.000000  35.000000
mean   18.000000  74.657143
std    10.246951  16.401117
min     1.000000  18.000000
25%     9.500000  62.500000
50%    18.000000  79.000000
75%    26.500000  88.000000
max    35.000000  96.000000

In [16]:
# Removed row with two NULLs
df = df.drop(26)

# Added a gender to the row missing a gender
df.loc[8,"gender"] = "male"

In [17]:
df['class'] = df['class'].replace('Fifth', 'Five')

In [19]:
# Filter students who achieved the average or above
df[df["mark"] >= df["mark"].mean()]

    id         name  class  mark  gender
0    1     John Deo   Four    75  female
1    2     Max Ruin  Three    85    male
6    7  My John Rob   Five    78    male
7    8       Asruid   Five    85    male
8    9      Tes Qry    Six    78    male
10  11       Ronald    Six    89  female
11  12        Recky    Six    94  female
12  13          Kty  Seven    88  female
13  14         Bigy  Seven    88  female
14  15     Tade Row    NaN    88    male
15  16        Gimmy   Four    88    male
17  18        Honny   Five    75    male
22  23        Herod  Eight    79    male
23  24    Tiddy Now  Seven    78    male
24  25     Giff Tow  Seven    88    male
25  26       Crelea  Seven    79    male
27  28    Rojj Base  Seven    86  female
29  30    Reppy Red    Six    79  female
30  31  Marry Toeey   Four    88    male
31  32    Binn Rott  Seven    90  female
32  33    Kenn Rein    Six    96  female
34  35   Rows Noump    Six    88  female

In [23]:
# Sort students by mark from highest to lowest
df = df.sort_values(by="mark", ascending=False)
df.head()

    id         name  class  mark  gender grade
32  33    Kenn Rein    Six    96  female     A
11  12        Recky    Six    94  female     A
31  32    Binn Rott  Seven    90  female     A
10  11       Ronald    Six    89  female     A
30  31  Marry Toeey   Four    88    male     A

In [22]:
# Creates a new column called grade and assigns a grade based on each student's mark

df.loc[df["mark"] >= 85, "grade"] = "A"
df.loc[(df["mark"] >= 70) & (df["mark"] <= 84), "grade"] = "B"
df.loc[(df["mark"] >= 60) & (df["mark"] <= 69), "grade"] = "C"
df.loc[df["mark"] < 60, "grade"] = "D"

df.head()

    id         name  class  mark  gender grade
32  33    Kenn Rein    Six    96  female     A
11  12        Recky    Six    94  female     A
31  32    Binn Rott  Seven    90  female     A
10  11       Ronald    Six    89  female     A
30  31  Marry Toeey   Four    88    male     A